name = "krypt-terminal-unified"
main = "workers/krypt-worker-unified.js"
compatibility_date = "2024-01-01"

# KV Namespaces for unified worker
[[kv_namespaces]]
binding = "KRYPT_DATA"
id = "1cfdd55d3f4b4b8f972d54ca074b1da9"
preview_id = "1cfdd55d3f4b4b8f972d54ca074b1da9"

[[kv_namespaces]]
binding = "EARLY_ACCESS"
id = "b465f2964e3d4fb2ad7cd164dee8a343"
preview_id = "b465f2964e3d4fb2ad7cd164dee8a343"

# Scheduled triggers for autonomous development
[triggers]
crons = ["*/5 * * * *"]  # Every 5 minutes

# Environment variables
[vars]
DEVELOPMENT_MODE = "production"
COMPONENTS_TOTAL = "4500"